create table warehouse(
    Id INTEGER generated by DEFAULT as IDENTITY PRIMARY KEY,
    Name varchar(50) not null UNIQUE
);
create table stock(
    Id INTEGER GENERATED by DEFAULT as IDENTITY PRIMARY KEY,
    WarehouseId integer REFERENCES warehouse(Id),
    Name varchar(50) not null
);
create table product(
    Id INTEGER GENERATED by DEFAULT as IDENTITY PRIMARY KEY,
    Sku varchar(100) not null UNIQUE,
    Name varchar(50) not null
);
create table stockItem(
    StockId INTEGER REFERENCES stock(Id),
    ProductId INTEGER REFERENCES product(Id),
    Quantity INTEGER not null,
    Reserved integer not null
);
create table suplier(
    Id integer GENERATED by DEFAULT as IDENTITY PRIMARY KEY,
    Name varchar(50) not null UNIQUE
);
create table shipment(
    Id INTEGER GENERATED by DEFAULT as IDENTITY PRIMARY KEY,
    WarehouseId INTEGER REFERENCES warehouse(Id),
    StockId INTEGER REFERENCES stock(Id),
    SuplierId INTEGER REFERENCES suplier(Id)
);
create table shipmentItem(
    ShipmentId INTEGER REFERENCES shipment(Id),
    ProductId INTEGER REFERENCES product(Id),
    Quantity INTEGER not null
);
