create table Warehouse(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(50) not null UNIQUE,
    Country varchar(50) not null,
    City varchar(50) not null
);


create TABLE Stock(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name varchar(100) not null,
    StockUnits integer not null check(StockUnits>=0),
    ReservedUnits integer not null check(ReservedUnits<=StockUnits),
    WarehouseId integer references Warehouse(Id)
);

create table Product(
    Id INTEGER GENERATED by DEFAULT as IDENTITY PRIMARY key,
    Name VARCHAR(100) not null UNIQUE,
    Description varchar(500),
    Price real not null check(Price>0),
    Quantity integer not null check(Quantity>0),
    StockId INTEGER REFERENCES Stock(Id)
);

create table Supplier(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name varchar(50) not null UNIQUE,
    Email varchar(100) not null UNIQUE,
    Phone varchar(20) not null UNIQUE,
    Address varchar(100) not null UNIQUE,
);

create table Shipment(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ShipmentNumber varchar(100) not null UNIQUE,
    ExpectedDate TIMESTAMP not null,
    ReceivedDate TIMESTAMP,
    ShipmentStatus varchar(10) check(ShipmentStatus in ('Created', 'InTransit', 'Delivered', 'Received', 'Canceled')),
    ShippingFee REAL not null check(ShippingFee>=0),
    SupplierId INTEGER REFERENCES Supplier(Id),
    WarehouseId INTEGER REFERENCES Warehouse(Id)
);


create table ShippingItem(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Quantity INTEGER not null check (Quantity > 0),
    UnitCost REAL not null check (UnitCost >= 0),
    ShipmentId INTEGER REFERENCES Shipment(Id),
    ProductId INTEGER REFERENCES Product(Id)
);

