create table Product(
    Id INTEGER GENERATED by DEFAULT as IDENTITY PRIMARY key,
    Name VARCHAR(100) not null UNIQUE,
    Description varchar(500),
    Price real not null check(Price>0),
    Created_at TIMESTAMP not null DEFAULT now(),
    Updated_at TIMESTAMP,
    Stock_id INTEGER REFERENCES Stock(Id)
);

INSERT INTO Product (Name,Price) values ('Test',200);
select * from Product;

create table Warehouse(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(50) not null UNIQUE,
    Country varchar(50) not null,
    City varchar(50) not null,
    Email varchar(100) not null UNIQUE,
    Capacity INTEGER not null check(Capacity>=0),
    Created_at TIMESTAMP not null,
    Updated_at TIMESTAMP
);

alter table Warehouse alter COLUMN Created_at set DEFAULT now();

create table Supplier(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name varchar(50) not null UNIQUE,
    Email varchar(100) not null UNIQUE,
    Phone varchar(20) not null UNIQUE,
    Address varchar(100) not null UNIQUE,
    IsActive BOOLEAN not null,
    Created_at TIMESTAMP not null,
    Updated_at TIMESTAMP
);

alter table Supplier alter column Created_at set DEFAULT now();

create TABLE Stock(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name varchar(100) not null,
    Warehouse_id INTEGER REFERENCES Warehouse(Id),
    Quantity INTEGER not null check(Quantity>=0),
    Reserved_quantity INTEGER not null check(Reserved_quantity<=Quantity),
    Created_at TIMESTAMP not null DEFAULT now(),
    Updated_at TIMESTAMP
);


create table Shipment(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Shipment_number varchar(100) not null UNIQUE,
    Supplier_id INTEGER REFERENCES Supplier(Id),
    Warehouse_id INTEGER REFERENCES Warehouse(Id),
    Expected_date TIMESTAMP not null,
    Received_date TIMESTAMP,
    Shipment_status varchar(10) check(Shipment_status in ('Created', 'InTransit', 'Delivered', 'Received', 'Canceled')),
    Tracking_number varchar(100) not null UNIQUE,
    Shipping_fee REAL not null check(Shipping_fee>=0),
    Notes VARCHAR(200), 
    Created_at TIMESTAMP not null,
    Updated_at TIMESTAMP
);

alter table Shipment alter COLUMN Created_at set DEFAULT now();

create table ShippingItem(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Shipment_id INTEGER REFERENCES Shipment(Id),
    Product_id INTEGER REFERENCES Product(Id),
    Quantity INTEGER not null check (Quantity > 0),
    Unit_cost REAL not null check (Unit_cost >= 0)
);

